### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by lawchihon** [firebaseui/ionic-authentication#1]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

macOS Sierra

### Versions

node: v6.10.2
npm: 3.10.10
Angular: 5.2.10

### Repro steps

Failed to find @firebaseui/ionic-authentication while using npm
npm install --save @firebaseui/ionic-authentication

Even if installed by github repo, still cannot find @firebaseui/ionic-authentication while using import

**Comment by AnthonyNahas** [comment]
thanks for showing your interest to this package. This project stills under development and is not been published yet. That's why you can't at the moment install this module via npm
